//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksListWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [Required(ErrorMessage = "A description for the task is required")]
        public string Description { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool Completion { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
